# Generated by Django 5.1.15 on 2026-10-07 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_expiryitem_billing_cycle_expiryitem_cancel_url_and_more'),
        ('notifications', '0001_initial'),
        ('support', '0003_inquiry_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='support.inquiry'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='for_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='items.expiryitem'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('expiry', '만료 예정'), ('payment', '결제 예정'), ('inquiry_reply', '문의 답변')], default='expiry', max_length=20),
        ),
    ]
