# Generated by Django 5.1.15 on 2026-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', '무료'), ('basic', '베이직'), ('pro', '프로')], default='free', max_length=20),
        ),
    ]
