# Generated by Django 5.1.15 on 2026-08-24 05:15

from django.db import migrations, models


def backfill_signup_source(apps, schema_editor):
    """기존 유저 중 kakao_id가 있는 유저는 signup_source를 kakao로 되짚어 채운다.

    이 필드가 생기기 전에는 kakao_id 유무로만 카카오 유저를 구분했으므로,
    이미 존재하는 카카오 유저들이 기본값(email)으로 잘못 표시되지 않게 한다.
    """
    User = apps.get_model("accounts", "User")
    User.objects.filter(kakao_id__isnull=False).update(signup_source="kakao")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signup_source",
            field=models.CharField(
                choices=[("email", "이메일"), ("kakao", "카카오"), ("google", "구글")],
                default="email",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_signup_source, migrations.RunPython.noop),
    ]
