# Generated by Django 5.1.15 on 2026-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
