# Generated by Django 5.1.15 on 2026-10-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_inquiry_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
