# Generated by Django 5.1.15 on 2026-08-21 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('subscription', '구독'), ('contract', '계약'), ('warranty', '보증'), ('membership', '멤버십'), ('insurance', '보험'), ('other', '기타')], default='other', max_length=20)),
                ('expiry_date', models.DateField()),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'expiry item',
                'verbose_name_plural': 'expiry items',
                'ordering': ['expiry_date'],
            },
        ),
    ]
