# Generated by Django 5.1.15 on 2026-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiryitem',
            name='notify_days_before',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
