# Generated by Django 5.1.15 on 2026-08-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_calendarnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiryitem',
            name='billing_cycle',
            field=models.CharField(choices=[('one_time', '1회성'), ('monthly', '매월'), ('yearly', '매년')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='expiryitem',
            name='cancel_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='expiryitem',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expiryitem',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
